# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsGroups20', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveNews',
            fields=[
                ('title', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('published_date', models.DateField(blank=True, primary_key=True)),
                ('published_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'live_news',
                'managed': False,
            },
        ),
    ]
