# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsGroups20', '0003_alchemynews_alchemynewsclassification'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveNewsClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('algorithm', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'live_news_classification',
            },
        ),
    ]
